---
version: "3.0"
services:
  app:
    build: .
    image: myhro/uri
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - .:/app
    working_dir: /app
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=uri
    volumes:
      - .:/app
    working_dir: /app
